#!/usr/bin/env python3
"""
Генерирует octopus_paths.js из SVG файла с нормализованными paths
"""

import re
from pathlib import Path
import xml.etree.ElementTree as ET

def normalize_path_to_absolute(path_d):
    """Конвертирует относительные path команды в абсолютные"""
    x, y = 0, 0
    result = []

    path_re = r'([MmLlCcQqZzHhVv])([^MmLlCcQqZzHhVv]*)'

    for match in re.finditer(path_re, path_d):
        cmd = match.group(1)
        args_str = match.group(2).strip()

        args = re.findall(r'-?\d+\.?\d*(?:[eE][-+]?\d+)?', args_str)
        nums = [float(arg) for arg in args]

        try:
            if cmd == 'M':
                x, y = nums[0], nums[1]
                result.append(f'M{x} {y}')
            elif cmd == 'm':
                x += nums[0]
                y += nums[1]
                result.append(f'M{x} {y}')
            elif cmd == 'L':
                x, y = nums[0], nums[1]
                result.append(f'L{x} {y}')
            elif cmd == 'l':
                x += nums[0]
                y += nums[1]
                result.append(f'L{x} {y}')
            elif cmd == 'C':
                result.append(f'C{nums[0]} {nums[1]} {nums[2]} {nums[3]} {nums[4]} {nums[5]}')
                x, y = nums[4], nums[5]
            elif cmd == 'c':
                c1x, c1y = x + nums[0], y + nums[1]
                c2x, c2y = x + nums[2], y + nums[3]
                x, y = x + nums[4], y + nums[5]
                result.append(f'C{c1x} {c1y} {c2x} {c2y} {x} {y}')
            elif cmd == 'Q':
                result.append(f'Q{nums[0]} {nums[1]} {nums[2]} {nums[3]}')
                x, y = nums[2], nums[3]
            elif cmd == 'q':
                cpx, cpy = x + nums[0], y + nums[1]
                x, y = x + nums[2], y + nums[3]
                result.append(f'Q{cpx} {cpy} {x} {y}')
            elif cmd == 'H':
                x = nums[0]
                result.append(f'L{x} {y}')
            elif cmd == 'h':
                x += nums[0]
                result.append(f'L{x} {y}')
            elif cmd == 'V':
                y = nums[0]
                result.append(f'L{x} {y}')
            elif cmd == 'v':
                y += nums[0]
                result.append(f'L{x} {y}')
            elif cmd in 'Zz':
                result.append('Z')
        except (IndexError, ValueError):
            pass

    return ''.join(result)

def extract_paths_from_svg(svg_path):
    """Извлекает все path элементы из SVG"""
    tree = ET.parse(svg_path)
    root = tree.getroot()

    # Пространство имён SVG
    ns = {'svg': 'http://www.w3.org/2000/svg'}

    paths = []
    for idx, path_elem in enumerate(root.findall('.//svg:path', ns)):
        d = path_elem.get('d', '')
        if d:
            # Нормализуем в абсолютные команды
            d_normalized = normalize_path_to_absolute(d)
            paths.append({
                'index': idx,
                'd': d_normalized,
                'color': path_elem.get('fill', '#000000'),
            })

    return paths

def generate_octopus_paths_js(paths):
    """Генерирует JavaScript код с paths"""
    code = '// Auto-generated octopus SVG paths\n'
    code += '// Generated by generate_octopus_paths.py\n\n'
    code += f'window.OCTOPUS_PATHS = [\n'

    for path in paths:
        # Экранируем кавычки в path данных
        d_escaped = path['d'].replace('"', '\\"')
        code += f'    {{ color: "{path["color"]}", d: "{d_escaped}" }},\n'

    code += '];\n'

    return code

def main():
    svg_path = Path('frontend/svg/octopus.svg')
    output_path = Path('frontend/octopus_paths.js')

    if not svg_path.exists():
        print(f"❌ SVG file not found: {svg_path}")
        return False

    print(f"📂 Loading SVG from {svg_path}...")
    paths = extract_paths_from_svg(svg_path)
    print(f"✅ Found {len(paths)} paths")

    print(f"📝 Generating JavaScript...")
    code = generate_octopus_paths_js(paths)

    print(f"💾 Writing to {output_path}...")
    output_path.write_text(code)

    print(f"✅ Done! Created {output_path}")
    print(f"   {len(paths)} paths with normalized (absolute) coordinates")

    return True

if __name__ == '__main__':
    main()
